{
    'name': 'Apple Pay Payment Integration',
    'summary': 'Integrate Apple Pay as a payment method in Odoo',
    'version': '1.0',
    'author': "Basem Walid",
    'maintainer': "Basem Walid",
    'website': "https://www.linkedin.com/in/basem-walid600/",
    'sequence': -1,
    'category': 'Accounting',
    'license': "AGPL-3",
    'depends': ['payment', 'account'],
    'data': [
        'views/payment_views.xml',
        'views/payment_popup_template.xml',
        'data/payment_acquirer_data.xml',
    ],
    'application': True,
    'installable': True,
    'auto_install': False,
}